# Generated by Django 5.2.1 on 2025-07-14 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNutritionData",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("meal_type", models.CharField(db_column="meal_type", max_length=100)),
                ("meal_date", models.DateField(auto_now=True, db_column="meal_date")),
                ("food_quantity", models.IntegerField(db_column="food_quantity")),
                ("food_name", models.CharField(db_column="food_name", max_length=500)),
                ("kcal", models.FloatField(blank=True, db_column="kcal", null=True)),
                (
                    "protein",
                    models.FloatField(blank=True, db_column="protein", null=True),
                ),
                ("carbs", models.FloatField(blank=True, db_column="carbs", null=True)),
                ("fats", models.FloatField(blank=True, db_column="fats", null=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.userdata",
                    ),
                ),
            ],
            options={"db_table": "user_nutrition_data",},
        ),
    ]
