# Generated by Django 5.2.1 on 2025-07-14 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[
                            ("Cardio", "Cardio"),
                            ("Weight Lifting", "Weight Lifting"),
                        ],
                        max_length=50,
                    ),
                ),
                ("exercise_name", models.CharField(max_length=200)),
                (
                    "intensity",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "kcal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("log_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="user.userdata",
                    ),
                ),
            ],
            options={"db_table": "exercise", "ordering": ["-log_date"],},
        ),
        migrations.CreateModel(
            name="Cardio",
            fields=[
                (
                    "exercise",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="cardio_details",
                        serialize=False,
                        to="exercise.exercise",
                    ),
                ),
                ("duration_minutes", models.PositiveIntegerField()),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
            ],
            options={"db_table": "cardio",},
        ),
        migrations.CreateModel(
            name="WeightLifting",
            fields=[
                (
                    "exercise",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="weight_lifting_details",
                        serialize=False,
                        to="exercise.exercise",
                    ),
                ),
                ("weight_kg", models.DecimalField(decimal_places=2, max_digits=5)),
                ("sets", models.PositiveIntegerField()),
                ("reps", models.PositiveIntegerField()),
            ],
            options={"db_table": "weightlifting",},
        ),
    ]
