# Generated by Django 5.2.1 on 2025-07-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="log_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
