# Generated by Django 5.2.1 on 2025-08-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0004_alter_exercise_log_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="log_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
