# Generated by Django 5.2.1 on 2025-07-14 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "user_id",
                    models.AutoField(
                        db_column="user_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_column="email", max_length=254, unique=True),
                ),
                ("password", models.CharField(db_column="password", max_length=150)),
                ("active", models.BooleanField(default=True)),
            ],
            options={"db_table": "user_data",},
        ),
        migrations.CreateModel(
            name="ProfileSetUp",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                (
                    "username",
                    models.CharField(
                        db_column="username", default="guest", max_length=150
                    ),
                ),
                ("height", models.IntegerField(db_column="height")),
                ("weight", models.IntegerField(db_column="weight")),
                ("goal", models.IntegerField(db_column="goal")),
                ("dob", models.DateField(db_column="dob")),
                ("gender", models.CharField(db_column="gender", max_length=100)),
                (
                    "activity_level",
                    models.CharField(db_column="activity_level", max_length=200),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.userdata",
                    ),
                ),
            ],
            options={"db_table": "user_profile",},
        ),
    ]
